// Generated by gencpp from file robot_msg/SetMapRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_MSG_MESSAGE_SETMAPREQUEST_H
#define ROBOT_MSG_MESSAGE_SETMAPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msg
{
template <class ContainerAllocator>
struct SetMapRequest_
{
  typedef SetMapRequest_<ContainerAllocator> Type;

  SetMapRequest_()
    : cmd()
    , name()  {
    }
  SetMapRequest_(const ContainerAllocator& _alloc)
    : cmd(_alloc)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _cmd_type;
  _cmd_type cmd;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::robot_msg::SetMapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msg::SetMapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetMapRequest_

typedef ::robot_msg::SetMapRequest_<std::allocator<void> > SetMapRequest;

typedef boost::shared_ptr< ::robot_msg::SetMapRequest > SetMapRequestPtr;
typedef boost::shared_ptr< ::robot_msg::SetMapRequest const> SetMapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msg::SetMapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msg::SetMapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msg::SetMapRequest_<ContainerAllocator1> & lhs, const ::robot_msg::SetMapRequest_<ContainerAllocator2> & rhs)
{
  return lhs.cmd == rhs.cmd &&
    lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msg::SetMapRequest_<ContainerAllocator1> & lhs, const ::robot_msg::SetMapRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_msg::SetMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msg::SetMapRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msg::SetMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msg::SetMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msg::SetMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msg::SetMapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msg::SetMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d4390008817d72fc39cb7de220158164";
  }

  static const char* value(const ::robot_msg::SetMapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd4390008817d72fcULL;
  static const uint64_t static_value2 = 0x39cb7de220158164ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msg::SetMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msg/SetMapRequest";
  }

  static const char* value(const ::robot_msg::SetMapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msg::SetMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# srv definition\n"
"\n"
"#request constants\n"
"\n"
"#   \"building_map\",     构建地图\n"
"#   \"save_map\",         保存地图\n"
"#   \"loading_map\",      加载地图\n"
"\n"
"#request fields\n"
"string  cmd     # 地图操作命令\n"
"string  name    # 地图名称\n"
;
  }

  static const char* value(const ::robot_msg::SetMapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msg::SetMapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetMapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msg::SetMapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msg::SetMapRequest_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.cmd);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSG_MESSAGE_SETMAPREQUEST_H
